name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
        
      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node --version
          npm --version
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: |
          npm run build
          echo "Build completed successfully"
          ls -la dist/
        
      - name: Deploy to GitHub Pages
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create or switch to gh-pages branch
          git checkout --orphan gh-pages
          git rm -rf .
          
          # Copy built files
          cp -r dist/* .
          cp dist/.* . 2>/dev/null || true
          
          # Create .nojekyll file
          touch .nojekyll
          
          # Add and commit files
          git add .
          git commit -m "Deploy to GitHub Pages - ${{ github.sha }}"
          
          # Push to gh-pages branch
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
          
          echo "Deployment completed successfully"